# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  namespace: crypt-system
  replicaCount: 1

image:
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

# replace storeType with valid store type, enable the associated store and add any environment variables required.
storeType: invalid
store:
  consul:
    enabled: false
    env: {}
  vault:
    enabled: false
    env: {}

serviceaccount:
  name: default
  namespace: default

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}