/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/bluehoodie/crypt-controller/pkg/apis/crypt/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCrypts implements CryptInterface
type FakeCrypts struct {
	Fake *FakeCoreV1alpha1
	ns   string
}

var cryptsResource = schema.GroupVersionResource{Group: "core.bluehoodie.io", Version: "v1alpha1", Resource: "crypts"}

var cryptsKind = schema.GroupVersionKind{Group: "core.bluehoodie.io", Version: "v1alpha1", Kind: "Crypt"}

// Get takes name of the crypt, and returns the corresponding crypt object, and an error if there is any.
func (c *FakeCrypts) Get(name string, options v1.GetOptions) (result *v1alpha1.Crypt, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cryptsResource, c.ns, name), &v1alpha1.Crypt{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Crypt), err
}

// List takes label and field selectors, and returns the list of Crypts that match those selectors.
func (c *FakeCrypts) List(opts v1.ListOptions) (result *v1alpha1.CryptList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cryptsResource, cryptsKind, c.ns, opts), &v1alpha1.CryptList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CryptList{ListMeta: obj.(*v1alpha1.CryptList).ListMeta}
	for _, item := range obj.(*v1alpha1.CryptList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested crypts.
func (c *FakeCrypts) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cryptsResource, c.ns, opts))

}

// Create takes the representation of a crypt and creates it.  Returns the server's representation of the crypt, and an error, if there is any.
func (c *FakeCrypts) Create(crypt *v1alpha1.Crypt) (result *v1alpha1.Crypt, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cryptsResource, c.ns, crypt), &v1alpha1.Crypt{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Crypt), err
}

// Update takes the representation of a crypt and updates it. Returns the server's representation of the crypt, and an error, if there is any.
func (c *FakeCrypts) Update(crypt *v1alpha1.Crypt) (result *v1alpha1.Crypt, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cryptsResource, c.ns, crypt), &v1alpha1.Crypt{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Crypt), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCrypts) UpdateStatus(crypt *v1alpha1.Crypt) (*v1alpha1.Crypt, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(cryptsResource, "status", c.ns, crypt), &v1alpha1.Crypt{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Crypt), err
}

// Delete takes name of the crypt and deletes it. Returns an error if one occurs.
func (c *FakeCrypts) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(cryptsResource, c.ns, name), &v1alpha1.Crypt{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCrypts) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cryptsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.CryptList{})
	return err
}

// Patch applies the patch and returns the patched crypt.
func (c *FakeCrypts) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Crypt, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cryptsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Crypt{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Crypt), err
}
