---
apiVersion: v1
kind: Pod
metadata:
  name: crypt-controller
  namespace: default
spec:
  containers:
    - image: bluehoodie/crypt-controller:latest
      imagePullPolicy: Always
      name: crypt-controller
      env:
        - name: STORE_TYPE
          valueFrom:
            configMapKeyRef:
              name: crypt-controller-config
              key: store-type
        - name: CONSUL_HTTP_ADDR
          valueFrom:
            configMapKeyRef:
              name: crypt-controller-config
              key: consul-address
  restartPolicy: Always
