apiVersion: core.bluehoodie.io/v1alpha1
kind: Crypt
metadata:
  name: test-crypt
  namespace: default
spec:
  secrets:
    - name: foo
      key: crypt/dev/foo
    - name: bar
      key: crypt/dev/bar
  namespaces:
    - dev-*
