kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: crypt-controller-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - "services"
      - "namespaces"
      - "pods"
    verbs:
      - "get"
      - "watch"
      - "list"
  - apiGroups:
      - "core.bluehoodie.io"
    resources:
      - "crypts"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "update"
  - apiGroups:
      - ""
    resources:
      - "events"
    verbs:
      - "create"
      - "update"
      - "patch"
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"