sudo: required
language: go
env:
  - GO111MODULE=off
go:
  - 1.11.x
services:
  - docker
git:
  depth: 1
install: true
script:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - go test -v -race ./...
after_success:
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then docker build --rm -t bluehoodie/crypt-controller .; fi
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then docker login -u="$DOCKERHUB_LOGIN" -p="$DOCKERHUB_PASSWORD"; fi
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then docker push bluehoodie/crypt-controller; fi
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH != "master" ]]; then docker tag bluehoodie/crypt-controller:latest bluehoodie/crypt-controller:$TRAVIS_BRANCH && docker push bluehoodie/crypt-controller; fi
