apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crypt-controller.fullname" . }}
  namespace: {{ .Values.deployment.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "crypt-controller.name" . }}
    helm.sh/chart: {{ include "crypt-controller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "crypt-controller.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "crypt-controller.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: STORE_TYPE
              value: {{ .Values.storeType }}
          envFrom:
            - configMapRef:
          {{- if .Values.store.consul.enabled }}
                name: {{ include "crypt-controller.name" . }}-consul-configmap
          {{- else if .Values.store.vault.enabled }}
                name: {{ include "crypt-controller.name" . }}-vault-configmap
          {{- end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}