kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "crypt-controller.name" . }}-clusterrole
rules:
  - apiGroups: ["core.bluehoodie.io"]
    resources: ["crypts"]
    verbs: ["get", "watch", "list", "update"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list", "create", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "crypt-controller.name" . }}-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "crypt-controller.name" . }}-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceaccount.name }}
    namespace: {{ .Values.serviceaccount.namespace }}