/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	cryptv1alpha1 "github.com/bluehoodie/crypt-controller/pkg/apis/crypt/v1alpha1"
	versioned "github.com/bluehoodie/crypt-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/bluehoodie/crypt-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/bluehoodie/crypt-controller/pkg/client/listers/crypt/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CryptInformer provides access to a shared informer and lister for
// Crypts.
type CryptInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.CryptLister
}

type cryptInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCryptInformer constructs a new informer for Crypt type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCryptInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCryptInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCryptInformer constructs a new informer for Crypt type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCryptInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1alpha1().Crypts(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1alpha1().Crypts(namespace).Watch(options)
			},
		},
		&cryptv1alpha1.Crypt{},
		resyncPeriod,
		indexers,
	)
}

func (f *cryptInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCryptInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *cryptInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cryptv1alpha1.Crypt{}, f.defaultInformer)
}

func (f *cryptInformer) Lister() v1alpha1.CryptLister {
	return v1alpha1.NewCryptLister(f.Informer().GetIndexer())
}
